### ISSUE TITLE
Error after executing the G28 Z command

### ISSUE THREAD

**Issue by egoleos** [ModularPrintingSystem/IDM#6]
Following an update, I encountered an issue after executing the G28 Z command, and the error message indicates: "MCU_trsync.start() missing 1 required positional argument: 'expire_timeout'".

```
Internal error on command:"G28"
Internal Error on WebRequest: gcode/script
Traceback (most recent call last):
  File "/home/egoleos/klipper/klippy/webhooks.py", line 256, in _process_request
    func(web_request)
  File "/home/egoleos/klipper/klippy/webhooks.py", line 436, in _handle_script
    self.gcode.run_script(web_request.get_str('script'))
  File "/home/egoleos/klipper/klippy/gcode.py", line 229, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/egoleos/klipper/klippy/gcode.py", line 211, in _process_commands
    handler(gcmd)
  File "/home/egoleos/klipper/klippy/extras/safe_z_home.py", line 79, in cmd_G28
    self.prev_G28(g28_gcmd)
  File "/home/egoleos/klipper/klippy/extras/homing.py", line 268, in cmd_G28
    kin.home(homing_state)
  File "/home/egoleos/klipper/klippy/kinematics/corexy.py", line 64, in home
    homing_state.home_rails([rail], forcepos, homepos)
  File "/home/egoleos/klipper/klippy/extras/homing.py", line 185, in home_rails
    hmove.homing_move(homepos, hi.speed)
  File "/home/egoleos/klipper/klippy/extras/homing.py", line 85, in homing_move
    wait = mcu_endstop.home_start(print_time, ENDSTOP_SAMPLE_TIME,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egoleos/klipper/klippy/extras/idm.py", line 1334, in home_start
    trsync.start(print_time, self._trigger_completion, expire_timeout)
TypeError: MCU_trsync.start() missing 1 required positional argument: 'expire_timeout' 
```

**Comment by ModularPrintingSystem** [comment]
I Fixed the Issue:
#7
